# Generated by Django 4.2.11 on 2024-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_remove_match_partner_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
