# Generated by Django 4.2.11 on 2024-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_match_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tenant',
        ),
    ]
