# Generated by Django 4.2.11 on 2024-06-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_alter_housing_tenants'),
        ('tenant', '0004_swipe_remove_match_partner_remove_match_tenant'),
        ('authentication', '0006_rename_desiredlocation_tenant_desiredcity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='swipe',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='authentication.tenant'),
        ),
        migrations.AddField(
            model_name='swipe',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='authentication.tenant'),
        ),
    ]
