# Generated by Django 4.2.11 on 2024-06-04 11:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_desiredlocation_tenant_desiredcity_and_more'),
        ('tenant', '0005_delete_match_swipe_partner_swipe_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(default=uuid.UUID('27f55501-2123-4906-9648-a1187211ea70'), editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant1', to='authentication.tenant')),
                ('tenant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant2', to='authentication.tenant')),
            ],
        ),
    ]
