# Generated by Django 4.2.11 on 2024-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_alter_match_match_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
