# Generated by Django 4.2.11 on 2024-05-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_landlord_fullname_landlord_phonenumber_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('match_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('paid1', models.BooleanField(default=False)),
                ('paid2', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.house')),
                ('tenants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.match')),
            ],
        ),
    ]
