# Generated by Django 4.2.11 on 2024-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='house',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='hosting_roommates',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
