# Generated by Django 4.2.11 on 2024-06-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_remove_house_rent_remove_house_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='state',
        ),
        migrations.AddField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
