# Generated by Django 4.2.11 on 2024-06-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0004_alter_house_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='square_feet',
            new_name='square_meters',
        ),
    ]
