# Generated by Django 4.2.11 on 2024-06-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_alter_match_match_id'),
        ('landlord', '0006_alter_housing_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='tenants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.match'),
        ),
    ]
