# Generated by Django 4.2.11 on 2024-06-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_alter_housing_tenants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='is_active',
            new_name='active',
        ),
    ]
