# Generated by Django 4.2.11 on 2024-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.useraccount',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.useraccount',),
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_student',
            new_name='is_landlord',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_teacher',
            new_name='is_user',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('USER', 'user'), ('LANDLORD', 'landlord')], default='LANDLORD', max_length=8),
        ),
    ]
