# Generated by Django 4.2.11 on 2024-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='noHouses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='desiredLocation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='roommate',
            field=models.BooleanField(null=True),
        ),
    ]
