# Generated by Django 4.2.11 on 2024-06-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_landlord_fullname_landlord_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='baseCity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
