# Generated by Django 4.2.11 on 2024-06-03 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_landlord_additional_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='desiredLocation',
            new_name='desiredCity',
        ),
        migrations.AddField(
            model_name='tenant',
            name='accountCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='desiredDistrict',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
